name: watch-wise

networks:
  proxy:
    name: proxy
    external: true

services:
  watch-wise:
    container_name: watch-wise
    pull_policy: build
    restart: unless-stopped
    image: watch-wise
    build:
      context: ../../
      dockerfile: Dockerfile
    env_file:
      - ../../stack.env
    networks:
      - proxy
    volumes:
      - ${VOLUME_DIR}/data:/usr/src/app/data

