/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  web: {
    CatalogSearch: () => import('#controllers/web/catalog_search_controller'),
    NewAccount: () => import('#controllers/web/new_account_controller'),
    Session: () => import('#controllers/web/session_controller'),
  },
}
