/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  api: {
    Library: () => import('#controllers/api/library_controller'),
  },
  web: {
    CatalogSearch: () => import('#controllers/web/catalog_search_controller'),
    Episodes: () => import('#controllers/web/episodes_controller'),
    Library: () => import('#controllers/web/library_controller'),
    Movies: () => import('#controllers/web/movies_controller'),
    NewAccount: () => import('#controllers/web/new_account_controller'),
    Session: () => import('#controllers/web/session_controller'),
  },
}
