/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const listeners = {
  UpdateSeriesProgress: () => import('#listeners/update_series_progress'),
  UpdateUserWatchedTime: () => import('#listeners/update_user_watched_time'),
}
