/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class LibraryEntrySchema extends BaseModel {
  static $columns = [
    'bannerPath',
    'createdAt',
    'id',
    'name',
    'posterPath',
    'progress',
    'provider',
    'providerId',
    'releasedAt',
    'summary',
    'type',
    'updatedAt',
    'userId',
  ] as const
  $columns = LibraryEntrySchema.$columns
  @column()
  declare bannerPath: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare posterPath: string | null
  @column()
  declare progress: number | null
  @column()
  declare provider: string
  @column()
  declare providerId: string
  @column.date()
  declare releasedAt: DateTime | null
  @column()
  declare summary: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'fullName',
    'id',
    'password',
    'updatedAt',
    'watchedTime',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare watchedTime: number
}

export class WatchedMarkSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'duration',
    'episode',
    'id',
    'libraryEntryId',
    'providerId',
    'season',
    'type',
    'updatedAt',
    'userId',
    'watchedAt',
  ] as const
  $columns = WatchedMarkSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare duration: number | null
  @column()
  declare episode: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare libraryEntryId: number
  @column()
  declare providerId: string
  @column()
  declare season: number | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column.dateTime()
  declare watchedAt: DateTime
}
