/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps, InferFlashData } from '@adonisjs/inertia/types'
import type CatalogEpisodeTransformer from '#transformers/catalog/episode_transformer'
import type CatalogSearchResultTransformer from '#transformers/catalog/search_result_transformer'
import type CatalogSerieTransformer from '#transformers/catalog/serie_transformer'
import type MovieTransformer from '#transformers/movie_transformer'
import type SerieTransformer from '#transformers/serie_transformer'
import type UserSettingsTransformer from '#transformers/user_settings_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type WatchedEpisodeTransformer from '#transformers/watched_episode_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export namespace Catalog {
    export type Episode = InferData<CatalogEpisodeTransformer>
    export namespace Episode {
      export type Variants = InferVariants<CatalogEpisodeTransformer>
    }
    export type SearchResult = InferData<CatalogSearchResultTransformer>
    export namespace SearchResult {
      export type Variants = InferVariants<CatalogSearchResultTransformer>
    }
    export type Serie = InferData<CatalogSerieTransformer>
    export namespace Serie {
      export type Variants = InferVariants<CatalogSerieTransformer>
    }
  }
  export type Movie = InferData<MovieTransformer>
  export namespace Movie {
    export type Variants = InferVariants<MovieTransformer>
  }
  export type Serie = InferData<SerieTransformer>
  export namespace Serie {
    export type Variants = InferVariants<SerieTransformer>
  }
  export type UserSettings = InferData<UserSettingsTransformer>
  export namespace UserSettings {
    export type Variants = InferVariants<UserSettingsTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type WatchedEpisode = InferData<WatchedEpisodeTransformer>
  export namespace WatchedEpisode {
    export type Variants = InferVariants<WatchedEpisodeTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
  export type FlashMessages = InferFlashData<InertiaMiddleware>
}
