/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="../../adonisrc.ts" />
/// <reference path="../../config/auth.ts" />
/// <reference path="../../config/cache.ts" />
/// <reference path="../../config/catalog_provider.ts" />
/// <reference path="../../config/hash.ts" />
/// <reference path="../../config/logger.ts" />
/// <reference path="../../config/radarr_provider.ts" />
/// <reference path="../../config/sonarr_provider.ts" />
